export default [
    {   id: "1",
        link : "https://www.tailbits.com/",
        img : "/assets/thumbnails/1.jpg",
        title : "Tailwind Component Library",
        description : "Tailbits is a library of UI components that are made with Tailwind CSS. We have created.... ",
        items: "Tailbits",
    },
    {   id: "2",
        link : "https://tailwindui.com/",
        img : "/assets/ui kit/image1.jpg",
        title : "Build your next idea even faster.",
        description : "Beautifully designed, expertly crafted components and templates, built by the makers of Tailwind CSS...",
        items: "Tailwind ui", 
    },
    {   id: "3",
        link : "https://www.tailwind-kit.com/",
        img : "/assets/thumbnails/Ngoding.jpg",
        title : "Components and templates for Tailwind CSS ",
        description : "Tail-kit gives you access to over 250 free components and free templates... ",    
        items: "Tail-kit", 
    },
    {   id: "4",
        link : "https://www.creative-tim.com/learning-lab/tailwind-starter-kit/presentation",
        img : "/assets/thumbnails/Ngoding.jpg",
        title : "A beautiful extension for TailwindCSS. ",
        description : "Tailwind Starter Kit is Free and Open Source. It does not change or add any CSS...  ",    
        items: "Tailwind starter kit", 
    },
    {   id: "5",
        link : "https://treact.owaiskhan.me/",
        img : "/assets/thumbnails/Ngoding.jpg",
        title : "Free Modern React Templates for every need. ",
        description : "Easily customizable modern React UI Templates and Components built using TailwindCSS...  ",   
        items: "Treact", 
    },
    {   id: "6",
        link : "https://tailwind-cards.netlify.app/",
        img : "/assets/thumbnails/Ngoding.jpg",
        title : "Responsive Cards ",
        description : "A growing collection of responsive text/image cards you can use/copy-paste in your tailwind css projects.  ",    
        items: "Responsive card", 
    },
    {   id: "7",
        link : "https://merakiui.com/",
        img : "/assets/thumbnails/Ngoding.jpg",
        title : "Modern - Customizable Tailwind CSS UI Components.",
        description : "Meraki UI is a collection of responsive Tailwind CSS components.... ",    
        items: "Meraki ui", 
    },
    {   id: "8",
        link : "https://www.tailwindtoolbox.com/",
        img : "/assets/thumbnails/Ngoding.jpg",
        title : "Free Tailwind CSS Templates, Components and Resources",
        description : "Open source starter templates and components, a directory of handy building kits... ",
        items: "Tailwind toolbox",     
    },
    {   id: "9",
        link : "https://kutty.netlify.app/?source=post_page-----80ec3d380b33--------------------------------",
        img : "/assets/thumbnails/Ngoding.jpg",
        title : "Prebuilt Tailwind Components",
        description : "Kutty is a tailwind plugin for building web applications. It has a set... ",  
        items: "Kutty",   
    },
    {   id: "10",
        link : "https://mynaui.com/?source=post_page-----80ec3d380b33--------------------------------",
        img : "/assets/thumbnails/Ngoding.jpg",
        title : "Figma File and HTML Code with Tailwind CSS Design System",
        description : "Create stunning, modern web experiences instantly with Myna UI — a comprehensive.... ", 
        items: "Myna ui",    
    },
]