export default [
    {   id: "1",
        link : "/Blog/tailwindcss",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/1.jpg",
        title : "Mengenal lebih jauh apa itu tailwindcss",
        description : "Tailwind CSS adalah framework CSS yang dibuat oleh Adam Wathan, Jonathan Reinink, David Hemphill... ",
        date: "Sabtu, 13 jan 2024",
        tags1: "Getting Started ",
    },
    {   id: "2",
        link : "/Blog/toolsui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/toolsui.jpg",
        title : "List Kumpulan Tailwind UI Kit dan Tailwind UI Block",
        description : "UI kits adalah istilah yang sering digunakan dalam pengembangan antarmuka pengguna (UI) untuk aplikasi web atau mobile....",
        date: "Senin, 15 jan 2024",
        tags1: "tailwind css",
        tags2: "ui components",
        
    },
    {   id: "3",
        link : "/Blog/loadimage",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/3.jpg",
        title : "Membuat Lazy Load Image Dengan Efek Blur",
        description : "Gambar adalah komponen terberat dari sebuah situs web. Gambar mencegah situs web memuat lebih cepat... ",
        date: "Sabtu, 13 jan 2024",
        tags1: "astro",
    
    },
    {   id: "4",
        link : "/Blog/headlessui",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/Ngoding.jpg",
        title : "Implementasi headless ui dalam project react",
        description : "implementasi shadcn ui di dalam project "
    },
    {   id: "5",
        link : "https://ervinarviandi.vercel.app/",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/Ngoding.jpg",
        title : "isntal shadcn ui di ext js",
        description : "implementasi shadcn ui di dalam project "
    },
    {   id: "6",
        link : "https://ervinarviandi.vercel.app/",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/Ngoding.jpg",
        title : "isntal shadcn ui di ext js",
        description : "implementasi shadcn ui di dalam project "
    },
    {   id: "7",
        link : "https://ervinarviandi.vercel.app/",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/Ngoding.jpg",
        title : "isntal shadcn ui di ext js",
        description : "implementasi shadcn ui di dalam project "
    },
    {   id: "8",
        link : "https://ervinarviandi.vercel.app/",
        profile : "/assets/profile/ervinarviandi.jpg",
        img : "/assets/thumbnails/Ngoding.jpg",
        title : "isntal shadcn ui di ext js",
        description : "implementasi shadcn ui di dalam project "
    },
]